on:
  # Trigger analysis when pushing to your main branches, and when creating a pull request.
  push:
    branches: ["main"] 

name: Main Workflow
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0
    - name: setup JDK 11
      uses: actions/setup-java@v2
      with:
          java-version: '11'
          distribution: 'adopt'		
    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@v4.0.0 # Ex: v4.0.0, See the latest version at https://github.com/marketplace/actions/sonarcloud-scan
      with:
         scannerVersion: 6.2.0.4584
         projectBaseDir: MyWebApp/src
         args: >
          -Dsonar.organization=organizationanw
          -Dsonar.projectKey=afzalanwar_SonarQube1
          -Dsonar.sources=.
          #-Dsonar.tests=tests/
          -Dsonar.verbose=true
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
